version: "3"

services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  gateway-ms:
    build: ./gateway-ms
    ports:
      - "${GATEWAY_MS_PORT}:${GATEWAY_MS_PORT}"
    volumes:
      - ./gateway-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${GATEWAY_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms:
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${USER_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - APP_EMAIL_PASSWORD=${APP_EMAIL_PASSWORD}
      - EMAIL=${EMAIL}
      - FRONTEND_URL=${FRONTEND_URL}
  # profile-ms:
  #   build: ./profile-ms
  #   volumes:
  #     - ./profile-ms/src:/usr/src/app/src
  #   ports:
  #     - "3002:3002"
  #   command: npm run start:dev
  #   environment:
  #     - PORT=3002
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DATABASE_URL=${USER_DATABASE_URL}
  products-ms:
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    ports:
      - "3003:3003"
    command: npm run start:dev
    environment:
      - PORT=3003
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${PRODUCTS_DATABASE_URL}
  # review-ms:
  #   build: ./review-ms
  #   volumes:
  #     - ./review-ms/src:/usr/src/app/src
  #   ports:
  #     - "3004:3004"
  #   command: npm run start:dev
  #   environment:
  #     - PORT=3004
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DATABASE_URL=${REVIEW_DATABASE_URL}
  #   depends_on:
  #     - nats-server
  cart-ms:
    build: ./cart-ms
    volumes:
      - ./cart-ms/src:/usr/src/app/src
    ports:
      - "3005:3005"
    command: npm run start:dev
    environment:
      - PORT=3005
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${CART_DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_CART_URL}

  # attributes-ms:
  #   build: ./attributes-ms
  #   volumes:
  #     - ./attributes-ms/src:/usr/src/app/src
  #   ports:
  #     - "3006:3006"
  #   command: npm run start:dev
  #   environment:
  #     - PORT=3006
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DATABASE_URL=${ATTRIBUTES_DATABASE_URL}
  #   depends_on:
  #     - nats-server

  # image-ms:
  #   build: ./image-ms
  #   volumes:
  #     - ./image-ms/src:/usr/src/app/src
  #   ports:
  #     - "3007:3007"
  #   command: npm run start:dev
  #   environment:
  #     - PORT=3007
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DATABASE_URL=${IMAGES_DATABASE_URL}
  #   depends_on:
  #     - nats-server

  orders-ms:
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    ports:
      - "3008:3008"
    command: npm run start:dev
    environment:
      - PORT=3008
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  payments-ms:
    container_name: payments-ms
    build: ./payments-ms
    volumes:   
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    ports:
      - 3007:3007
    environment: 
      - PORT=3007
      - NATS_SERVERS=nats://nats-server:4222 
      - DATABASE_URL=${PAYMENTS_DATABASE_URL}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}