version: "3"

services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  gateway-ms:
    build: ./gateway-ms
    ports:
      - "${GATEWAY_MS_PORT}:3000"
    volumes:
      - ./gateway-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${GATEWAY_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms:
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    ports:
      - "3001:3001"
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    ports:
      - "3002:3002"
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${PRODUCTS_DATABASE_URL}

  cart-ms:
    build: ./cart-ms
    volumes:   
      - ./cart-ms/src:/usr/src/app/src
    ports:
      - "3005:3005"
    command: npm run start:dev
    environment: 
      - PORT=3005
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${CART_DATABASE_URL}