apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-ms
  name: auth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-ms
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/main-stack-446713-e6/backend-tic/auth-ms
          name: auth-ms
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats:4222"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: database_url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwt_secret
            - name: APP_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: app_email_password
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: email
            - name: FRONTEND_URL
              value: "http://localhost:3000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
status: {}
