steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/main-stack-446713-e6/backend-tic/gateway-ms',
        '-f',
        'gateway-ms/dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/main-stack-446713-e6/backend-tic/gateway-ms',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
