steps:
  # Paso 1: Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_DOCKER_REPO}/gateway-ms',
        '-f',
        'gateway-ms/dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]

  # Paso 2: Publicar la imagen en Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_DOCKER_REPO}/gateway-ms']

  # Paso 3: Autenticarse contra el clúster de Kubernetes
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_CLUSTER_REGION}',
      ]

  # Paso 4: Actualizar el despliegue con Helm
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'helm upgrade gateway-ms ./k8s --install --atomic --set image.repository=${_DOCKER_REPO}/gateway-ms,image.tag=${COMMIT_SHA} --namespace default',
      ]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _CLUSTER_NAME: 'tic-backend-gke'
  _CLUSTER_REGION: 'southamerica-east1'
  _DOCKER_REPO: 'us-central1-docker.pkg.dev/main-stack-446713-e6/backend-tic'
