apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gateway-ms
  name: gateway-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway-ms
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/main-stack-446713-e6/backend-tic/gateway-ms
          name: gateway-ms
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats"
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
