apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gateway-ms
  name: gateway-ms
spec:
  ports:
    - name: "3000"
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: gateway-ms
  type: NodePort
status:
  loadBalancer: {}
